version: '3.9'

networks:
  app-network-microservice:
    external: true

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-mitra
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_tubes_mitra
    networks:
      app-network-microservice:
        aliases:
          - mysql-mitra
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis-mitra
    networks:
      app-network-microservice:
        aliases:
          - redis-mitra

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-mitra
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - "8082:80"
    networks:
      - app-network-microservice

  service-mitra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-mitra
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_HOST: mysql-mitra
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db_tubes_mitra
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 12345
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 9002
    networks:
      - app-network-microservice
    restart: on-failure